language: java
sudo: false
install: true
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
      - graphviz
        
jdk: oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    
cache:
  directories:
  - $HOME/.m2

script:
  - cp parent-pom/toolchain/toolchains.xml $HOME/.m2/toolchains.xml  
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)

