language: java
sudo: false
install: true
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java-installer      
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
  - cp parent-pom/toolchain/toolchains.xml $HOME/.m2/toolchains.xml  
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


