AWSTemplateFormatVersion: '2010-09-09'
Resources:
  defaulttopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: pether@hack23.com
          Protocol: email
      TopicName: default-topic
  EventRuleCloudTrailChanges:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-cloudtrail-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to CloudTrail configutation
        and publishes change events to an SNS topic for notification.
      State: ENABLED
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - cloudtrail.amazonaws.com
          eventName:
            - StopLogging
            - DeleteTrail
            - UpdateTrail
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
  EventRuleConfigChanges:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-config-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to AWS Config and publishes
        change events to an SNS topic for notification.
      State: ENABLED
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - config.amazonaws.com
          eventName:
            - PutConfigurationRecorder
            - StopConfigurationRecorder
            - DeleteDeliveryChannel
            - PutDeliveryChannel
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
  EventRuleGuardDuty:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-guardduty-finding
      Description: >-
        A CloudWatch Event Rule that triggers on Amazon GuardDuty findings. The
        Event Rule can be used to trigger notifications or remediative actions
        using AWS Lambda.
      State: ENABLED
      EventPattern:
        detail-type:
          - GuardDuty Finding
        detail:
          eventSource:
            - aws.guardduty
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
  EventRuleMacie:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-macie-alert
      Description: >-
        A Macie Event Rule that triggers on Macie alerts. The
        Event Rule can be used to trigger notifications or remediative actions
        using AWS Lambda.
      State: ENABLED
      EventPattern:
        detail-type:
          - Macie Alert
        detail:
          eventSource:
            - aws.macie
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
  EventRulejGsAC:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-network-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to network configuration
        and publishes change events to an SNS topic for notification.
      State: ENABLED
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - ec2.amazonaws.com
          eventName:
            - AttachInternetGateway
            - AssociateRouteTable
            - CreateCustomerGateway
            - CreateInternetGateway
            - CreateRoute
            - CreateRouteTable
            - DeleteCustomerGateway
            - DeleteInternetGateway
            - DeleteRoute
            - DeleteRouteTable
            - DeleteDhcpOptions
            - DetachInternetGateway
            - DisassociateRouteTable
            - ReplaceRoute
            - ReplaceRouteTableAssociation
  EventRuleOVRwV:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-iam-policy-changes
      Description: >-
        A CloudWatch Event Rule that detects IAM policy changes and publishes
        change events to an SNS topic for notification.
      State: ENABLED
      Targets:
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - iam.amazonaws.com
          eventName:
            - CreateAccessKey
            - DeleteAccessKey
            - DeleteRolePolicy
            - DeleteUserPolicy
            - PutGroupPolicy
            - PutRolePolicy
            - PutUserPolicy
            - CreatePolicy
            - DeletePolicy
            - CreatePolicyVersion
            - DeletePolicyVersion
            - AttachRolePolicy
            - DetachRolePolicy
            - AttachUserPolicy
            - DetachUserPolicy
            - AttachGroupPolicy
            - DetachGroupPolicy
  EventRulephbWD:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-s3-bucket-policy-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to S3 bucket policies and
        publishes change events to an SNS topic for notification.
      State: ENABLED
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - PutBucketAcl
            - PutBucketPolicy
            - PutBucketCors
            - PutBucketLifecycle
            - PutBucketReplication
            - DeleteBucketPolicy
            - DeleteBucketCors
            - DeleteBucketLifecycle
            - DeleteBucketReplication
  EventRulepNgXx:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-config-rule-compliance-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to AWS Config Rule
        compliance status and publishes change events to an SNS topic for
        notification.
      State: ENABLED
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
      EventPattern:
        detail-type:
          - Config Rules Compliance Change
        source:
          - aws.config
  EventRuledRZuL:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-security-group-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to security groups and
        publishes change events to an SNS topic for notification.
      State: ENABLED
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - ec2.amazonaws.com
          eventName:
            - AuthorizeSecurityGroupIngress
            - AuthorizeSecurityGroupEgress
            - RevokeSecurityGroupIngress
            - RevokeSecurityGroupEgress
            - CreateSecurityGroup
            - DeleteSecurityGroup          
Parameters: {}
Metadata: {}
Conditions: {}

