AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EventRulezCHsT:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-cloudtrail-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to CloudTrail configutation
        and publishes change events to an SNS topic for notification.
      State: ENABLED
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - cloudtrail.amazonaws.com
          eventName:
            - StopLogging
            - DeleteTrail
            - UpdateTrail
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
  defaulttopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Endpoint: pether@hack23.com
          Protocol: email
      TopicName: default-topic
  EventRuleNtrab:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: detect-config-changes
      Description: >-
        A CloudWatch Event Rule that detects changes to AWS Config and publishes
        change events to an SNS topic for notification.
      State: ENABLED
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - config.amazonaws.com
          eventName:
            - PutConfigurationRecorder
            - StopConfigurationRecorder
            - DeleteDeliveryChannel
            - PutDeliveryChannel
      Targets:
        - Arn:
            Ref: defaulttopic
          Id: target-id1
Parameters: {}
Metadata: {}
Conditions: {}
